name: Build

on:
  push:
    branches:
      - master
  release:
    types: 
      - published

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Create version file
      run: make version

    - name: Store version file
      uses: actions/upload-artifact@v1
      with:
        name: version
        path: target/dist/common/lib/peppol/version

  linux64:
    name: Linux (amd64)
    runs-on: ubuntu-latest
    needs: init

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Fetch version file
      uses: actions/download-artifact@v1
      with:
        name: version
        path: target/dist/common/lib/peppol/version

#    - name: Library cache
#      id: cache
#      uses: actions/cache@v1
#      with:
#        path: tmp
#        key: libs

    - name: Prepare files
      env:
        GITHUB_TOKEN: ${{ secrets.SUDO_GITHUB_TOKEN }}
      run: make clean fetch-linux-amd64 version

    - name: Build tar.gz
      run: make package-linux-amd64-tar

    - name: Build Debian package
      run: make package-linux-amd64-deb

    - name: Build RPM package
      run: make package-linux-amd64-rpm

    - name: List packages
      run: ls -lh target/pkg

    - name: Build Docker image
      run: make docker

    - name: Upload tar.gz
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/pkg/linux-amd64.tar.gz
        name: pdk-linux-amd64-${TAG}.tar.gz
        label: Linux Package (amd64)

    - name: Upload Debian package
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/pkg/linux-amd64.deb
        name: pdk-linux-amd64-${TAG}.deb
        label: Linux DEB Package (amd64)

    - name: Upload RPM package
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/pkg/linux-amd64.rpm
        name: pdk-linux-amd64-${TAG}.rpm
        label: Linux RPM Package (amd64)

    - name: Push edge image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        docker login -u ${DOCKER_USERNAME} -p ${DOCKER_TOKEN}
        docker tag openpeppol/pdk:dev klakegg/pdk:edge
        docker push klakegg/pdk:edge

    - name: Push tagged image
      if: startsWith(github.ref, 'refs/tags/')
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        TAG=$(echo $GITHUB_REF | sed "s:.*/::g")
        docker login -u ${DOCKER_USERNAME} -p ${DOCKER_TOKEN}
        docker tag openpeppol/pdk:dev klakegg/pdk:$TAG
        docker push klakegg/pdk:$TAG


  macos64:
    name: MacOS (amd64)
    runs-on: ubuntu-latest
    needs: init

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Fetch version file
      uses: actions/download-artifact@v1
      with:
        name: version
        path: target/dist/common/lib/peppol/version

    - name: Prepare files
      env:
        GITHUB_TOKEN: ${{ secrets.SUDO_GITHUB_TOKEN }}
      run: make clean fetch-macos-amd64 version

    - name: Build tar.gz
      run: make package-macos-amd64-tar

    - name: Build app
      run: make package-macos-amd64-app

    - name: Build brew formula
      run: make package-macos-amd64-brew

    - name: List packages
      run: ls -lh target/pkg

    - name: Upload tar.gz
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/pkg/macos-amd64.tar.gz
        name: pdk-macos-amd64-${TAG}.tar.gz
        label: MacOS Package (amd64)

    - name: Upload app
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/pkg/macos-amd64.app.tar.gz
        name: pdk-macos-amd64-${TAG}.app.tar.gz
        label: MacOS App Package (amd64)

    - name: Upload brew formula
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/pkg/peppol-pdk.rb
        name: peppol-pdk.rb
        label: MacOS Brew Formula (amd64)


  win32:
    name: Windows (i386)
    runs-on: ubuntu-latest
    needs: init

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Fetch version file
      uses: actions/download-artifact@v1
      with:
        name: version
        path: target/dist/common/lib/peppol/version

    - name: Prepare files
      env:
        GITHUB_TOKEN: ${{ secrets.SUDO_GITHUB_TOKEN }}
      run: make clean fetch-win32 version

    - name: Build zip
      run: make package-win32-zip

    - name: Build Windows Installer
      run: make package-win32-wix

    - name: List packages
      run: ls -lh target/pkg

    - name: Upload zip
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/pkg/win32.zip
        name: pdk-win32-${TAG}.zip
        label: Windows Package (32-bit)

    - name: Upload Windows Installer
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/pkg/win32.msi
        name: pdk-win32-${TAG}.msi
        label: Windows Installer (32-bit)


  win64:
    name: Windows (amd64)
    runs-on: ubuntu-latest
    needs: init

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Fetch version file
      uses: actions/download-artifact@v1
      with:
        name: version
        path: target/dist/common/lib/peppol/version

    - name: Prepare files
      env:
        GITHUB_TOKEN: ${{ secrets.SUDO_GITHUB_TOKEN }}
      run: make clean fetch-win64 version

    - name: Build zip
      run: make package-win64-zip

    - name: Build Windows Installer
      run: make package-win64-wix

    - name: List packages
      run: ls -lh target/pkg

    - name: Upload zip
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/pkg/win64.zip
        name: pdk-win64-${TAG}.zip
        label: Windows Package (64-bit)

    - name: Upload Windows Installer
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/pkg/win64.msi
        name: pdk-win64-${TAG}.msi
        label: Windows Installer (64-bit)
