name: Build

on:
  push:
    branches:
      - master
  release:
    types: 
      - published

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Library cache
      id: cache
      uses: actions/cache@v1
      with:
        path: tmp
        key: libs

    - name: Prepare files
      run: make clean fetch

    - name: Create packages
      run: make package

    - name: Build Docker image
      run: make docker

    - name: Push edge image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        docker login -u ${DOCKER_USERNAME} -p ${DOCKER_TOKEN}
        docker tag openpeppol/pdk:dev klakegg/pdk:edge
        docker push klakegg/pdk:edge

    - name: Upload build artifacts
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        script:
          upload \
            -f target/pkg/linux64.tar.gz \
            -n pdk-linux64-${TAG}.tar.gz
          upload \
            -f target/pkg/macos64.tar.gz \
            -n pdk-macos64-${TAG}.tar.gz
          upload \
            -f target/pkg/win32.zip \
            -n pdk-win32-${TAG}.zip
          upload \
            -f target/pkg/win64.zip \
            -n pdk-win64-${TAG}.zip

    - name: Push tagged image
      if: startsWith(github.ref, 'refs/tags/')
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        TAG=$(echo $GITHUB_REF | sed "s:.*/::g")
        docker login -u ${DOCKER_USERNAME} -p ${DOCKER_TOKEN}
        docker tag openpeppol/pdk:dev klakegg/pdk:$TAG
        docker push klakegg/pdk:$TAG