name: Build

on:
  push:
    branches:
      - master
  release:
    types: 
      - published

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Library cache
      id: cache
      uses: actions/cache@v1
      with:
        path: tmp
        key: libs

    - name: Build distributions
      run: make

    - name: Build Docker image
      run: make docker

    - name: Upload build artifacts
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: target/pkg/*.zip
        type: application/zip
