name: Build

on:
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Create version file
        run: make version

      - name: Store version file
        uses: actions/upload-artifact@v1
        with:
          name: version
          path: target/dist/common/lib/peppol/version

  linux-amd64:
    name: Linux (amd64)
    runs-on: ubuntu-latest
    needs: init

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Prepare version labels
        uses: k15g/action-version-labels@v1
        with:
          prefix: project

      - name: Fetch version file
        uses: actions/download-artifact@v1
        with:
          name: version
          path: target/dist/common/lib/peppol/version

      - name: Prepare files
        env:
          GITHUB_USERNAME: ${{ secrets.SUDO_GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.SUDO_GITHUB_TOKEN }}
        run: make clean fetch-linux-amd64 version

      - name: Build tar.gz
        run: make package-linux-amd64-tar

      - name: Build Debian package
        run: make package-linux-amd64-deb

      - name: Build RPM package
        run: make package-linux-amd64-rpm

      - name: List packages
        run: ls -lh target/pkg

      - name: Build Docker image
        run: make docker

      - name: Upload tar.gz
        uses: k15g/action-github-asset-upload@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: target/pkg/linux-amd64.tar.gz
          name: pdk-linux-amd64-${{ env.PROJECT_VERSION }}.tar.gz
          label: Linux Package (amd64)

      - name: Upload Debian package
        uses: k15g/action-github-asset-upload@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: target/pkg/linux-amd64.deb
          name: pdk-linux-amd64-${{ env.PROJECT_VERSION }}.deb
          label: Linux DEB Package (amd64)

      - name: Upload RPM package
        uses: k15g/action-github-asset-upload@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: target/pkg/linux-amd64.rpm
          name: pdk-linux-amd64-${{ env.PROJECT_VERSION }}.rpm
          label: Linux RPM Package (amd64)

      - name: Push edge image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_TOKEN}
          docker tag openpeppol/pdk:dev klakegg/pdk:edge
          docker push klakegg/pdk:edge

      - name: Push tagged image
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_TOKEN}
          docker tag openpeppol/pdk:dev klakegg/pdk:${{ env.PROJECT_VERSION }}
          docker push klakegg/pdk:${{ env.PROJECT_VERSION }}

  linux-arm64:
    name: Linux (arm64)
    runs-on: ubuntu-latest
    needs: init

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Prepare version labels
        uses: k15g/action-version-labels@v1
        with:
          prefix: project

      - name: Fetch version file
        uses: actions/download-artifact@v1
        with:
          name: version
          path: target/dist/common/lib/peppol/version

      - name: Prepare files
        env:
          GITHUB_USERNAME: ${{ secrets.SUDO_GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.SUDO_GITHUB_TOKEN }}
        run: make clean fetch-linux-arm64 version

      - name: Build tar.gz
        run: make package-linux-arm64-tar

      - name: List packages
        run: ls -lh target/pkg

      - name: Upload tar.gz
        uses: k15g/action-github-asset-upload@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: target/pkg/linux-arm64.tar.gz
          name: pdk-linux-arm64-${{ env.PROJECT_VERSION }}.tar.gz
          label: Linux Package (arm64)

  macos64:
    name: MacOS (amd64)
    runs-on: ubuntu-latest
    needs: init

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Prepare version labels
        uses: k15g/action-version-labels@v1
        with:
          prefix: project

      - name: Fetch version file
        uses: actions/download-artifact@v1
        with:
          name: version
          path: target/dist/common/lib/peppol/version

      - name: Prepare files
        env:
          GITHUB_USERNAME: ${{ secrets.SUDO_GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.SUDO_GITHUB_TOKEN }}
        run: make clean fetch-macos-amd64 version

      - name: Build tar.gz
        run: make package-macos-amd64-tar

      - name: Build app
        run: make package-macos-amd64-app

      - name: Build brew formula
        run: make package-macos-amd64-brew

      - name: List packages
        run: ls -lh target/pkg

      - name: Upload tar.gz
        uses: k15g/action-github-asset-upload@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: target/pkg/macos-amd64.tar.gz
          name: pdk-macos-amd64-${{ env.PROJECT_VERSION }}.tar.gz
          label: MacOS Package (amd64)

      - name: Upload app
        uses: k15g/action-github-asset-upload@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: target/pkg/macos-amd64.app.tar.gz
          name: pdk-macos-amd64-${{ env.PROJECT_VERSION }}.app.tar.gz
          label: MacOS App Package (amd64)

      - name: Upload brew formula
        uses: k15g/action-github-asset-upload@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: target/pkg/peppol-pdk.rb
          name: peppol-pdk.rb
          label: MacOS Brew Formula (amd64)

  win64:
    name: Windows (amd64)
    runs-on: ubuntu-latest
    needs: init

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Prepare version labels
        uses: k15g/action-version-labels@v1
        with:
          prefix: project

      - name: Fetch version file
        uses: actions/download-artifact@v1
        with:
          name: version
          path: target/dist/common/lib/peppol/version

      - name: Prepare files
        env:
          GITHUB_USERNAME: ${{ secrets.SUDO_GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.SUDO_GITHUB_TOKEN }}
        run: make clean fetch-win-amd64 version

      - name: Build zip
        run: make package-win-amd64-zip

      #- name: Build Windows Installer
      #  run: make package-win-amd64-wix

      - name: List packages
        run: ls -lh target/pkg

      - name: Upload zip
        uses: k15g/action-github-asset-upload@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: target/pkg/win-amd64.zip
          name: pdk-win-amd64-${{ env.PROJECT_VERSION }}.zip
          label: Windows Package (64-bit)

    #  - name: Upload Windows Installer
    #    uses: k15g/action-github-asset-upload@v1
    #    if: startsWith(github.ref, 'refs/tags/v')
    #    with:
    #      token: ${{ secrets.GITHUB_TOKEN }}
    #      file: target/pkg/win64.msi
    #      name: pdk-win-amd64-${{ env.PROJECT_VERSION }}.msi
    #      label: Windows Installer (64-bit)
