name: Build

on:
  push:
    branches:
      - master
  release:
    types: 
      - published

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Create version file
      run: make version

    - name: Store version file
      uses: actions/upload-artifact@v1
      with:
        name: version
        path: target/dist/common/lib/peppol/version

  linux64:
    name: Linux 64-bit
    runs-on: ubuntu-latest
    needs: init

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Fetch version file
      uses: actions/download-artifact@v1
      with:
        name: version
        path: target/dist/common/lib/peppol/version

#    - name: Library cache
#      id: cache
#      uses: actions/cache@v1
#      with:
#        path: tmp
#        key: libs

    - name: Prepare files
      run: make clean fetch-linux64 version

    - name: Build tar.gz
      run: make package-linux64-zip

    - name: Build Debian package
      run: make package-linux64-deb

    - name: Build RPM package
      run: make package-linux64-rpm

    - name: Build Docker image
      run: make docker

    - name: Upload tar.gz
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/pkg/linux64.tar.gz
        name: pdk-linux64-${TAG}.tar.gz

    - name: Upload Debian package
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/pkg/linux64.deb
        name: pdk-linux64-${TAG}.deb

    - name: Upload RPM package
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/pkg/linux64.rpm
        name: pdk-linux64-${TAG}.rpm

    - name: Push edge image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        docker login -u ${DOCKER_USERNAME} -p ${DOCKER_TOKEN}
        docker tag openpeppol/pdk:dev klakegg/pdk:edge
        docker push klakegg/pdk:edge

    - name: Push tagged image
      if: startsWith(github.ref, 'refs/tags/')
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        TAG=$(echo $GITHUB_REF | sed "s:.*/::g")
        docker login -u ${DOCKER_USERNAME} -p ${DOCKER_TOKEN}
        docker tag openpeppol/pdk:dev klakegg/pdk:$TAG
        docker push klakegg/pdk:$TAG


  macos64:
    name: MacOS 64-bit
    runs-on: ubuntu-latest
    needs: init

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Fetch version file
      uses: actions/download-artifact@v1
      with:
        name: version
        path: target/dist/common/lib/peppol/version

    - name: Prepare files
      run: make clean fetch-macos64 version

    - name: Build tar.gz
      run: make package-macos64-zip

    - name: Upload tar.gz
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/pkg/macos64.tar.gz
        name: pdk-macos64-${TAG}.tar.gz


  win32:
    name: Windows 32-bit
    runs-on: ubuntu-latest
    needs: init

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Fetch version file
      uses: actions/download-artifact@v1
      with:
        name: version
        path: target/dist/common/lib/peppol/version

    - name: Prepare files
      run: make clean fetch-win64 version

    - name: Build zip
      run: make package-win32-zip

    - name: Build Windows Installer
      run: make package-win32-wix

    - name: Upload zip
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/pkg/win32.zip
        name: pdk-win32-${TAG}.zip

    - name: Upload Windows Installer
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/pkg/win32.msi
        name: pdk-win32-${TAG}.msi


  win64:
    name: Windows 64-bit
    runs-on: ubuntu-latest
    needs: init

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Fetch version file
      uses: actions/download-artifact@v1
      with:
        name: version
        path: target/dist/common/lib/peppol/version

    - name: Prepare files
      run: make clean fetch-win64 version

    - name: Build zip
      run: make package-win64-zip

    - name: Build Windows Installer
      run: make package-win64-wix

    - name: Upload zip
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/pkg/win64.zip
        name: pdk-win64-${TAG}.zip

    - name: Upload Windows Installer
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/pkg/win64.msi
        name: pdk-win64-${TAG}.msi
